/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.MasterTravelSchedule;
import UserInterface.ManageAirliner.UpdateAirplane;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.ManageAirliner.ManageAirliners;
/**
 *
 * @author Mayank
 */
public class AddAirline extends javax.swing.JPanel {
    
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private MasterTravelSchedule masterTravelSchedule;
    private AirplaneDirectory airplaneDirectory;
    private Airliner airliner;
    /**
     * Creates new form ManageAirliners
     */
    public AddAirline(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, MasterTravelSchedule masterTravelSchedule) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.masterTravelSchedule = masterTravelSchedule;
        this.airliner = airliner;
        populateAirliners();
    }
    
    public void populateAirliners() {
        DefaultTableModel dtm = (DefaultTableModel)tblManageAirliners.getModel();
        dtm.setRowCount(0);
        for(Airliner a : airlineDirectory.getAirlinerList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]= a;
            row[1]= a.getFleetSize();
            row[2]= a.getHeadquarter();
            dtm.addRow(row);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageAirliners = new javax.swing.JTable();
        btnCreateAirliner = new javax.swing.JButton();
        updateAirlineBtn = new javax.swing.JButton();
        btnBackManageAirline = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tblManageAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airline Name", "Fleet Size", "Headquarters"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManageAirliners.setRowHeight(25);
        jScrollPane1.setViewportView(tblManageAirliners);
        if (tblManageAirliners.getColumnModel().getColumnCount() > 0) {
            tblManageAirliners.getColumnModel().getColumn(0).setResizable(false);
            tblManageAirliners.getColumnModel().getColumn(1).setResizable(false);
            tblManageAirliners.getColumnModel().getColumn(2).setResizable(false);
        }

        btnCreateAirliner.setText("Add Airline");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        updateAirlineBtn.setText("Update Airline");
        updateAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirlineBtnActionPerformed(evt);
            }
        });

        btnBackManageAirline.setText("<Back");
        btnBackManageAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackManageAirlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnBackManageAirline)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnCreateAirliner)
                .addGap(18, 18, 18)
                .addComponent(updateAirlineBtn)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackManageAirline)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAirliner)
                    .addComponent(updateAirlineBtn))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleParent(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        CreateAirliners createAirlinersPanel = new CreateAirliners(this.panel, airlineDirectory,  airplaneDirectory,  masterTravelSchedule);
        this.panel.add(createAirlinersPanel, "CreateAirliners");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnBackManageAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackManageAirlineActionPerformed
        // TODO add your handling code here:
        /*
        ManageTravelAgency manageTravelAgency = new ManageTravelAgency(this.panel, airlineDirectory);
        this.panel.add(manageTravelAgency, "ManageTravelAgency");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);*/
        
//        ManageAirliners manageAirliners = new ManageAirliners(this.panel,  airlineDirectory,  airplaneDirectory,  masterTravelSchedule);
//        this.panel.add(manageAirliners, "ManageAirliners");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
        this.panel.remove(this);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_btnBackManageAirlineActionPerformed

    private void updateAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirlineBtnActionPerformed
        int selectedRow = tblManageAirliners.getSelectedRow();
        if(selectedRow>=0){
            Airliner airliner = (Airliner)tblManageAirliners.getValueAt(selectedRow, 0);
            
            UpdateAirliner updateAirlinerPanel = new UpdateAirliner(this.panel,  airlineDirectory,  airplaneDirectory,  masterTravelSchedule, airliner);
            this.panel.add(updateAirlinerPanel, "UpdateAirliner");
            CardLayout layout = (CardLayout)this.panel.getLayout();
            layout.next(panel);
        }else{
            JOptionPane.showMessageDialog(null, "Please select an Airliner");
        }
    }//GEN-LAST:event_updateAirlineBtnActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        populateAirliners();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackManageAirline;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageAirliners;
    private javax.swing.JButton updateAirlineBtn;
    // End of variables declaration//GEN-END:variables
}
