/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.MasterTravelSchedule;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class ManageAirliners extends javax.swing.JPanel {
    
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private MasterTravelSchedule masterTravelSchedule;
    /**
     * Creates new form ManageAirliners
     */
    public ManageAirliners(JPanel panel, AirlinerDirectory airlineDirectory) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        //this.masterTravelSchedule = masterTravelSchedule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageAirliners = new javax.swing.JTable();
        btnCreateAirliner = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBackManageAirline = new javax.swing.JButton();

        tblManageAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblManageAirliners);

        btnCreateAirliner.setText("Create");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });

        jButton2.setText("View");

        btnBackManageAirline.setText("<Back");
        btnBackManageAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackManageAirlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnCreateAirliner)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackManageAirline)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackManageAirline)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAirliner)
                    .addComponent(jButton2))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleParent(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        CreateAirliners createAirlinersPanel = new CreateAirliners(this.panel, airlineDirectory);
        this.panel.add(createAirlinersPanel, "CreateAirliners");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnBackManageAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackManageAirlineActionPerformed
        // TODO add your handling code here:
        /*
        ManageTravelAgency manageTravelAgency = new ManageTravelAgency(this.panel, airlineDirectory);
        this.panel.add(manageTravelAgency, "ManageTravelAgency");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);*/
    }//GEN-LAST:event_btnBackManageAirlineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackManageAirline;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageAirliners;
    // End of variables declaration//GEN-END:variables
}
