/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Airplane;
import Business.CustomerDirectory;
import Business.Flight;
import Business.MasterTravelSchedule;
import Business.ReservationDirectory;
import Business.Seat;
import UserInterface.ManageAirliner.UpdateAirplane;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivibhatt
 */
public class SearchFlightJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlightJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private MasterTravelSchedule masterTravelSchedule;
    private ArrayList<Flight> masterFlightList;
    private String searchTxtFlight;
    private String source;
    private String destination;
    private CustomerDirectory custDir;
    private String searchType;
    private ReservationDirectory reservationDirectory;

    public SearchFlightJPanel1(JPanel panel, AirlinerDirectory airlineDirectory, MasterTravelSchedule masterTravelSchedule, CustomerDirectory custDir, ReservationDirectory reservationDirectory) {
        initComponents();
        searchType = "one-way";
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.masterTravelSchedule = masterTravelSchedule;
        this.custDir = custDir;
        this.reservationDirectory = reservationDirectory;
        populate();
        hideFields();
        
    }
    
    public void hideFields() {
        returningDate.setVisible(false);
        returningDateLbl.setVisible(false);
        tblSearchRoundTripFlights.setVisible(false);
        jScrollPane2.setVisible(false);
        jLabel2.setVisible(false);
    }
    public void showFields() {
        returningDate.setVisible(true);
        returningDateLbl.setVisible(true);
        
    }
    
    public void populate() {
        
        DefaultTableModel dtm = (DefaultTableModel) tblSearchFlight.getModel();
        dtm.setRowCount(0);
        for (Flight f : masterTravelSchedule.getMasterFlightList()) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = f;
            row[1] = f.getFlightSchedule().getSource();
            row[2] = f.getFlightSchedule().getDestination();
            row[3] = f.getFlightSchedule().getDepartureDate();
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightSearchOptions = new javax.swing.ButtonGroup();
        oneWayRB = new javax.swing.JRadioButton();
        multiCityRB = new javax.swing.JRadioButton();
        roundTripRB = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        sourceCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        destinationCombo = new javax.swing.JComboBox<>();
        departingDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        returningDateLbl = new javax.swing.JLabel();
        returningDate = new javax.swing.JTextField();
        searchFlight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchFlight = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchRoundTripFlights = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        flightSearchOptions.add(oneWayRB);
        oneWayRB.setSelected(true);
        oneWayRB.setText("One-way");
        oneWayRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayRBActionPerformed(evt);
            }
        });

        flightSearchOptions.add(multiCityRB);
        multiCityRB.setText("Multi-city");
        multiCityRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiCityRBActionPerformed(evt);
            }
        });

        flightSearchOptions.add(roundTripRB);
        roundTripRB.setText("Round-trip");
        roundTripRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripRBActionPerformed(evt);
            }
        });

        jLabel7.setText("Departing from?");

        sourceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Boston", "San Francisco", "Dallas", "San Jose", "Seattle", "New York", "Las Vegas", "Los Angeles", "Chicago", "Miami" }));

        jLabel8.setText("Going to?");

        destinationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Boston", "San Francisco", "Dallas", "San Jose", "Seattle", "New York", "Las Vegas", "Los Angeles", "Chicago", "Miami" }));

        jLabel9.setText("Departing Date");

        returningDateLbl.setText("Returning Date");

        searchFlight.setText("Search");
        searchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightActionPerformed(evt);
            }
        });

        tblSearchFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight #", "Source", "Destination", "Departing Date and Time", "Arrival Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearchFlight);
        if (tblSearchFlight.getColumnModel().getColumnCount() > 0) {
            tblSearchFlight.getColumnModel().getColumn(0).setResizable(false);
            tblSearchFlight.getColumnModel().getColumn(1).setResizable(false);
            tblSearchFlight.getColumnModel().getColumn(2).setResizable(false);
            tblSearchFlight.getColumnModel().getColumn(3).setResizable(false);
            tblSearchFlight.getColumnModel().getColumn(4).setResizable(false);
        }

        tblSearchRoundTripFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight #", "Source", "Destination", "Departing Date and Time", "Arrival Date and Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSearchRoundTripFlights);
        if (tblSearchRoundTripFlights.getColumnModel().getColumnCount() > 0) {
            tblSearchRoundTripFlights.getColumnModel().getColumn(0).setResizable(false);
            tblSearchRoundTripFlights.getColumnModel().getColumn(1).setResizable(false);
            tblSearchRoundTripFlights.getColumnModel().getColumn(2).setResizable(false);
            tblSearchRoundTripFlights.getColumnModel().getColumn(3).setResizable(false);
            tblSearchRoundTripFlights.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(oneWayRB)
                        .addGap(18, 18, 18)
                        .addComponent(roundTripRB)
                        .addGap(18, 18, 18)
                        .addComponent(multiCityRB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(departingDate)
                            .addComponent(sourceCombo, 0, 144, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returningDateLbl)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinationCombo, 0, 144, Short.MAX_VALUE)
                            .addComponent(returningDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(searchFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneWayRB)
                    .addComponent(roundTripRB)
                    .addComponent(multiCityRB))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(departingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returningDateLbl)
                    .addComponent(returningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(searchFlight)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(2362, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightActionPerformed
        System.out.println(oneWayRB.isSelected());
        System.out.println(multiCityRB.isSelected());
        System.out.println(roundTripRB.isSelected());
        
        if(oneWayRB.isSelected()) {
            jLabel1.setText("Flights from " + sourceCombo.getSelectedItem() + " to " + destinationCombo.getSelectedItem());
            String source = (String)sourceCombo.getSelectedItem();
            String destination = (String)destinationCombo.getSelectedItem();
            LocalDate dDate = LocalDate.parse(departingDate.getText());
            //LocalDate rDate = LocalDate.parse(returningDate.getText());
        
            DefaultTableModel dtm = (DefaultTableModel) tblSearchFlight.getModel();
            dtm.setRowCount(0);
            for (Flight f : masterTravelSchedule.searchOneWayFlight(source, destination, dDate)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getFlightSchedule().getSource();
                row[2] = f.getFlightSchedule().getDestination();
                row[3] = f.getFlightSchedule().getDepartureDate();
                dtm.addRow(row);
            }
        }
        
        if(roundTripRB.isSelected()) {
            tblSearchRoundTripFlights.setVisible(true);
            jScrollPane2.setVisible(true);
            jLabel2.setVisible(true);
            
            jLabel1.setText("Flights from " + sourceCombo.getSelectedItem() + " to " + destinationCombo.getSelectedItem());
            String source = (String)sourceCombo.getSelectedItem();
            String destination = (String)destinationCombo.getSelectedItem();
            LocalDate dDate = LocalDate.parse(departingDate.getText());
            LocalDate rDate = LocalDate.parse(returningDate.getText());
        
            DefaultTableModel dtm = (DefaultTableModel) tblSearchFlight.getModel();
            dtm.setRowCount(0);
            for (Flight f : masterTravelSchedule.searchRoundTripFlight(source, destination, dDate, null)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getFlightSchedule().getSource();
                row[2] = f.getFlightSchedule().getDestination();
                row[3] = f.getFlightSchedule().getDepartureDate();
                dtm.addRow(row);
            }
            
            jLabel2.setText("Flights from " + destinationCombo.getSelectedItem() + " to " + sourceCombo.getSelectedItem());
            DefaultTableModel dtm1 = (DefaultTableModel) tblSearchRoundTripFlights.getModel();
            dtm1.setRowCount(0);
            for (Flight f : masterTravelSchedule.searchRoundTripFlight(destination, source, null, rDate)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getFlightSchedule().getSource();
                row[2] = f.getFlightSchedule().getDestination();
                row[3] = f.getFlightSchedule().getDepartureDate();
                dtm1.addRow(row);
            }
        }
        
        if(multiCityRB.isSelected()) {
            String source = (String)sourceCombo.getSelectedItem();
            String destination = (String)destinationCombo.getSelectedItem();
            LocalDate dDate = LocalDate.parse(departingDate.getText());
            LocalDate rDate = LocalDate.parse(returningDate.getText());
        
            DefaultTableModel dtm = (DefaultTableModel) tblSearchFlight.getModel();
            dtm.setRowCount(0);
            for (Flight f : masterTravelSchedule.searchOneWayFlight(source, destination, dDate)) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = f;
                row[1] = f.getFlightSchedule().getSource();
                row[2] = f.getFlightSchedule().getDestination();
                row[3] = f.getFlightSchedule().getDepartureDate();
                dtm.addRow(row);
            }
        }
        
    }//GEN-LAST:event_searchFlightActionPerformed

    private void oneWayRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayRBActionPerformed
        System.out.println(oneWayRB.isSelected());
        hideFields();
        
    }//GEN-LAST:event_oneWayRBActionPerformed

    private void multiCityRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiCityRBActionPerformed
        System.out.println(multiCityRB.isSelected());
        hideFields();
    }//GEN-LAST:event_multiCityRBActionPerformed

    private void roundTripRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTripRBActionPerformed
        System.out.println(roundTripRB.isSelected());
        showFields();
    }//GEN-LAST:event_roundTripRBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int selectedRow1 = tblSearchFlight.getSelectedRow();
        int selectedRow2 = tblSearchRoundTripFlights.getSelectedRow();
        ArrayList<Flight> flightToBook = new ArrayList<>();
        
        if(selectedRow1<0) {
            JOptionPane.showMessageDialog(null, "Please select a Flight1");
        }
        else if(selectedRow2<0 && roundTripRB.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select a Flight2");
        }
        else {
            Flight f1;
            Flight f = (Flight)tblSearchFlight.getValueAt(selectedRow1, 0);
            if(roundTripRB.isSelected()) {
                f1 = (Flight)tblSearchRoundTripFlights.getValueAt(selectedRow2, 0);
                flightToBook.add(f1);
            }
            flightToBook.add(f);
            
            BookFlightJPanel1 searchFlightJPanel = new BookFlightJPanel1(this.panel, airlineDirectory, masterTravelSchedule, flightToBook, custDir, reservationDirectory);
            this.panel.add(searchFlightJPanel, "SearchFlightJPanel");
            CardLayout layout = (CardLayout)this.panel.getLayout();
            layout.next(panel);
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void populateSearch() {
        /*DefaultTableModel dtm = (DefaultTableModel) tblSearchFlight.getModel();
        dtm.setRowCount(0);
        for (Flight f : masterTravelSchedule.searchFlight(searchTxtFlight, source, destination)) {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = f;
            row[1] = f.getFlightSchedule().getSource();
            row[2] = f.getFlightSchedule().getDestination();
            dtm.addRow(row);
        }
          System.out.println("---------SEARCHED FLIGHTS------------");
          System.out.println("===>> SEARCHED FLIGHT" + masterTravelSchedule.searchFlight(searchTxtFlight, source, destination));
           */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField departingDate;
    private javax.swing.JComboBox<String> destinationCombo;
    private javax.swing.ButtonGroup flightSearchOptions;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton multiCityRB;
    private javax.swing.JRadioButton oneWayRB;
    private javax.swing.JTextField returningDate;
    private javax.swing.JLabel returningDateLbl;
    private javax.swing.JRadioButton roundTripRB;
    private javax.swing.JButton searchFlight;
    private javax.swing.JComboBox<String> sourceCombo;
    private javax.swing.JTable tblSearchFlight;
    private javax.swing.JTable tblSearchRoundTripFlights;
    // End of variables declaration//GEN-END:variables
}
