/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivibhatt
 */
public class UpdateCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerJPanel
     */
    private JPanel panel;
    private AirlinerDirectory airlineDirectory;
    private CustomerDirectory custDir;
    private Customer cust;
    private String gender;
    public UpdateCustomerJPanel(JPanel panel, AirlinerDirectory airlineDirectory,CustomerDirectory custDir, Customer cust) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.custDir = custDir;
        this.cust = cust;
        this.gender = "";
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
     private void displayProduct() {
         //Customer customer = new Customer();
         //System.out.println(custDir.getCust().getFirstName() + "GET ");
        updateFirstName.setText(custDir.getCust().getFirstName() + "");
        updateLastName.setText(custDir.getCust().getLastName() + "");
        updateEmailID.setText(custDir.getCust().getEmailId() + "");
        updatePassport.setText(custDir.getCust().getPassportNum()+ "");
        updateGender.setSelectedItem(custDir.getCust().getGender() + "");
       
        
  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkUpdateCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdateCustomer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updatePassport = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateEmailID = new javax.swing.JTextField();
        updateLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updateFirstName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        updateGender = new javax.swing.JComboBox<>();

        bkUpdateCustomer.setText("<<Back");
        bkUpdateCustomer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bkUpdateCustomerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        bkUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkUpdateCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE CUSTOMER");

        btnUpdateCustomer.setText("UPDATE");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender*");

        updatePassport.setEnabled(false);
        updatePassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassportActionPerformed(evt);
            }
        });

        jLabel6.setText("Passport # *");

        jLabel5.setText("Email*");

        updateEmailID.setEnabled(false);
        updateEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmailIDActionPerformed(evt);
            }
        });

        updateLastName.setEnabled(false);
        updateLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLastNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name*");

        jLabel3.setText("First Name*");

        updateFirstName.setEnabled(false);
        updateFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFirstNameActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        updateGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[None]", "Male", "Female" }));
        updateGender.setEnabled(false);
        updateGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkUpdateCustomer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addComponent(updateFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateEmailID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatePassport, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkUpdateCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePassport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCustomer)
                    .addComponent(btnSave))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePassportActionPerformed

    private void updateEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmailIDActionPerformed

    private void updateLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLastNameActionPerformed

    private void updateFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFirstNameActionPerformed

    private void bkUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkUpdateCustomerActionPerformed
        // TODO add your handling code here:
//        ManageCustomerJPanel manageCustomerJPanel = new ManageCustomerJPanel(this.panel, airlineDirectory, custDir, cust);
//        this.panel.add(manageCustomerJPanel, "ManageCustomerJPanel");
//        CardLayout layout = (CardLayout)this.panel.getLayout();
//        layout.next(panel);
//         this.panel.remove(this);
//        CardLayout layout = (CardLayout) this.panel.getLayout();
//        layout.previous(panel);
this.panel.remove(this);
        CardLayout layout = (CardLayout)this.panel.getLayout();
        Component[] comps = this.panel.getComponents();
        for (Component comp : comps){
            if(comp instanceof ManageCustomerJPanel){
                ManageCustomerJPanel rePopulateTable = (ManageCustomerJPanel) comp;
                rePopulateTable.populateManageCustomer();
            }
        }
        layout.previous(this.panel);
    }//GEN-LAST:event_bkUpdateCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        
         setAllEnabled(true);
        btnSave.setEnabled(true);
        btnUpdateCustomer.setEnabled(false);
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName =updateFirstName.getText();
   
        if (firstName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "First Name Cannot be empty");
            return;
        } else {
            firstName = updateFirstName.getText();
        }
        //Last Name
        String lastName = updateLastName.getText();
        if (lastName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Last Name Cannot be empty");
            return;
        } else {
            lastName = updateLastName.getText();
        }
        //Email 
        String email = updateEmailID.getText();
     if (email.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Email ID Cannot be empty");
            return;
        } else {
            email = updateEmailID.getText();
            
        }
        //Passport
        String passport = updatePassport.getText();
        if (passport.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Passport # Cannot be empty");
            return;
        } else {
            passport = updatePassport.getText();
            
        }
        
       
        if(gender.isEmpty()){
              JOptionPane.showMessageDialog(null, "Gender Cannot be empty");
            return;
        }
        
        //SetValues
       Customer customer = new Customer();
        customer.setFirstName(firstName);
        customer.setLastName(lastName);
        customer.setEmailId(email);
        customer.setPassportNum(passport);
        customer.setGender(gender);
        custDir.setCust(customer);
        
       
        
        btnSave.setEnabled(false);
        btnUpdateCustomer.setEnabled(true);

      JOptionPane.showMessageDialog(null, "Customer updated successfully");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void updateGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGenderActionPerformed
        // TODO add your handling code here:
        gender = (String) updateGender.getSelectedItem();   
    }//GEN-LAST:event_updateGenderActionPerformed

    private void bkUpdateCustomerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bkUpdateCustomerAncestorAdded
        // TODO add your handling code here:
   
    }//GEN-LAST:event_bkUpdateCustomerAncestorAdded

     private void setAllEnabled(boolean b) {
        updateFirstName.setEnabled(b);
        updateLastName.setEnabled(b);
        updateEmailID.setEnabled(b);
        updatePassport.setEnabled(b);
        updateGender.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkUpdateCustomer;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField updateEmailID;
    private javax.swing.JTextField updateFirstName;
    private javax.swing.JComboBox<String> updateGender;
    private javax.swing.JTextField updateLastName;
    private javax.swing.JTextField updatePassport;
    // End of variables declaration//GEN-END:variables
}
