/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.AirplaneDirectory;
import Business.Flight;
import Business.FlightSchedule;
import Business.MasterTravelSchedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayank
 */
public class AirlinerFunction extends javax.swing.JPanel {
    
    private AirlinerDirectory airlineDirectory;
    private AirplaneDirectory airplaneDirectory;
    private JPanel panel;
    private Airliner airliner;
    private MasterTravelSchedule masterTravelSchedule;
    /**
     * Creates new form AirlinerFunction
     */
    public AirlinerFunction(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, Airliner airliner, MasterTravelSchedule masterTravelSchedule) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.airliner = airliner;
        this.masterTravelSchedule = masterTravelSchedule;
        populateAirlineFlights();
    }
    
    public void populateAirlineFlights() {
        DefaultTableModel dtm = (DefaultTableModel)airlinerFlightTbl.getModel();
        dtm.setRowCount(0);
        for(Flight f : airliner.getFlightList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=f; //f.getFlightId();
            row[1]=f.getFlightSchedule().getSource();
            row[2]=f.getFlightSchedule().getDestination();
            row[4]=f.getAirplane();
            row[5]=(f.isIsActive()? "Active" : "Cancelled");
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageAirplaneBtn = new javax.swing.JButton();
        addFlightBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerFlightTbl = new javax.swing.JTable();
        manageflightScheduleBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updateFlightBtn = new javax.swing.JButton();

        manageAirplaneBtn.setText("Manage Airplane");
        manageAirplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirplaneBtnActionPerformed(evt);
            }
        });

        addFlightBtn.setText("Add Flight");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        airlinerFlightTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight #", "Source", "Destination", "Date", "Airplane", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airlinerFlightTbl);
        if (airlinerFlightTbl.getColumnModel().getColumnCount() > 0) {
            airlinerFlightTbl.getColumnModel().getColumn(0).setResizable(false);
            airlinerFlightTbl.getColumnModel().getColumn(1).setResizable(false);
            airlinerFlightTbl.getColumnModel().getColumn(2).setResizable(false);
            airlinerFlightTbl.getColumnModel().getColumn(3).setResizable(false);
            airlinerFlightTbl.getColumnModel().getColumn(4).setResizable(false);
            airlinerFlightTbl.getColumnModel().getColumn(5).setResizable(false);
        }

        manageflightScheduleBtn.setText("ManageFlight Schedule");
        manageflightScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageflightScheduleBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Flights List");

        updateFlightBtn.setText("Update Flight");
        updateFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(manageAirplaneBtn)
                .addGap(18, 18, 18)
                .addComponent(manageflightScheduleBtn)
                .addGap(18, 18, 18)
                .addComponent(addFlightBtn)
                .addGap(18, 18, 18)
                .addComponent(updateFlightBtn)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageAirplaneBtn)
                    .addComponent(addFlightBtn)
                    .addComponent(manageflightScheduleBtn)
                    .addComponent(updateFlightBtn))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirplaneBtnActionPerformed
        ManageAirplanes createAirplanePanel = new ManageAirplanes(this.panel, airlineDirectory, airplaneDirectory, airliner);
        this.panel.add(createAirplanePanel, "CreateAirplane");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_manageAirplaneBtnActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        CreateFlight createFlightPanel = new CreateFlight(this.panel, airlineDirectory, airplaneDirectory, airliner, masterTravelSchedule);
        this.panel.add(createFlightPanel, "CreateFlight");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void manageflightScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageflightScheduleBtnActionPerformed
        ManageFlightSchedules flightSchedulePanel = new ManageFlightSchedules(this.panel, airlineDirectory, airplaneDirectory, airliner);
        this.panel.add(flightSchedulePanel, "FlightSchedule");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_manageflightScheduleBtnActionPerformed

    private void updateFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightBtnActionPerformed
        int selectedRow = airlinerFlightTbl.getSelectedRow();
        if(selectedRow>=0){
            Flight flight = (Flight)airlinerFlightTbl.getValueAt(selectedRow, 0);
            
            UpdateFlight updateflightPanel = new UpdateFlight(this.panel, airlineDirectory, airplaneDirectory, airliner, flight);
            this.panel.add(updateflightPanel, "UpdateFlight");
            CardLayout layout = (CardLayout)this.panel.getLayout();
            layout.next(panel);
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_updateFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTable airlinerFlightTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageAirplaneBtn;
    private javax.swing.JButton manageflightScheduleBtn;
    private javax.swing.JButton updateFlightBtn;
    // End of variables declaration//GEN-END:variables
}
