/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.FlightSchedule;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.MasterTravelSchedule;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class CreateFlightSchedule extends javax.swing.JPanel {
    private AirlinerDirectory airlineDirectory;
    private AirplaneDirectory airplaneDirectory;
    private JPanel panel;
    private Airliner airliner;
    private MasterTravelSchedule masterTravelSchedule;
    /**
     * Creates new form CreateFlightSchedule
     */
    public CreateFlightSchedule(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, Airliner airliner,MasterTravelSchedule masterTravelSchedule) {
        initComponents();
        this.airliner = airliner;
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.masterTravelSchedule = masterTravelSchedule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departureDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        arrivalDate = new javax.swing.JTextField();
        createFlight = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        departureTime = new javax.swing.JTextField();
        arrivalTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sourceCombo = new javax.swing.JComboBox<>();
        destinationCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        backCreateFlightSchedule = new javax.swing.JButton();

        jLabel1.setText("Source *");

        jLabel2.setText("Destination *");

        jLabel3.setText("Departure Date *");

        departureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDateActionPerformed(evt);
            }
        });

        jLabel4.setText("Arrival Date *");

        createFlight.setText("Create");
        createFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFlightActionPerformed(evt);
            }
        });

        jLabel5.setText("Departure Time *");

        jLabel6.setText("Arrival time *");

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Create Flight Schedule");

        sourceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Boston", "San Francisco", "Dallas", "San Jose", "Seattle", "New York", "Las Vegas", "Los Angeles", "Chicago", "Miami" }));

        destinationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- None --", "Boston", "San Francisco", "Dallas", "San Jose", "Seattle", "New York", "Las Vegas", "Los Angeles", "Chicago", "Miami" }));

        jLabel8.setText("(YYYY-MM-DD)");

        jLabel9.setText("(YYYY-MM-DD)");

        jLabel10.setText("(HH:MM)");

        jLabel11.setText("(HH:MM)");

        backCreateFlightSchedule.setText("<<<Back");
        backCreateFlightSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateFlightScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(arrivalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(departureTime, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(arrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(departureDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(destinationCombo, 0, 203, Short.MAX_VALUE)
                                    .addComponent(sourceCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(createFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backCreateFlightSchedule)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backCreateFlightSchedule)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(destinationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(40, 40, 40)
                .addComponent(createFlight)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFlightActionPerformed
        
        /*FlightSchedule flightSchedule = new FlightSchedule();
        
        flightSchedule.setSource(source.getText());
        flightSchedule.setDestination(destination.getText());
        flightSchedule.setDepartureDate(LocalDate.parse(departureDate.getText()));
        flightSchedule.setArrivalDate(LocalDate.parse(arrivalDate.getText()));
        flightSchedule.setDepartureTime(LocalTime.parse(departureTime.getText()));
        flightSchedule.setArrivalTime(LocalTime.parse(arrivalTime.getText()));
        
        airliner.addFlightSchedule(flightSchedule);     */        
        
        if("-- None --".equals(sourceCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Source city is mandatory");
            
        }else if("-- None --".equals(destinationCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Destination city is mandatory");
            
        }else if("".equals(departureDate.getText())) {
            JOptionPane.showMessageDialog(null, "Departure date is mandatory");
            
        }else if("".equals(arrivalDate.getText())) {
            JOptionPane.showMessageDialog(null, "Arrival date is mandatory");
            
        }else if("".equals(departureTime.getText())) {
            JOptionPane.showMessageDialog(null, "Departure time is mandatory");
            
        }else if("".equals(arrivalTime.getText())) {
            JOptionPane.showMessageDialog(null, "Arrival time is mandatory");
            
        }else if(sourceCombo.getSelectedItem().equals(destinationCombo.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Source and destination city cannot be same");
            
        }else {            
            LocalDate dDate;
            LocalDate aDate;
            LocalTime dTime;
            LocalTime aTime;
            
            try{
                dDate = LocalDate.parse(departureDate.getText());
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid Departure date in YYYY-MM-DD format");
                return;
            } 
            
            try{
                aDate = LocalDate.parse(arrivalDate.getText());
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid Arrival date in YYYY-MM-DD format");
                return;
            } 
             
            try{
                dTime = LocalTime.parse(departureTime.getText());
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid Departure time in HH:MM format");
                return;
            }
            
            try{
                aTime = LocalTime.parse(arrivalTime.getText());
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Please enter a valid Arrival time in HH:MM format");
                return;
            } 
            
            if(dDate.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(null, "Departure Date can not be the past date");
            }else if(aDate.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(null, "Arrival Date can not be the past date");
            }else if(dDate.isAfter(aDate)) {
                JOptionPane.showMessageDialog(null, "Departure Date should not be greater than Arrival Date");
            }else if(dDate.equals(aDate) && dTime.isAfter(aTime)) {
                JOptionPane.showMessageDialog(null, "Departure Time should not be greater than Arrival Time");
            }else if(dDate.equals(aDate) && dTime.equals(aTime)) {
                JOptionPane.showMessageDialog(null, "Departure Time should not be same as Arrival Time");
            }else {
                FlightSchedule flightSchedule = new FlightSchedule();
        
                flightSchedule.setSource(sourceCombo.getSelectedItem().toString());
                flightSchedule.setDestination(destinationCombo.getSelectedItem().toString());
                flightSchedule.setDepartureDate(LocalDate.parse(departureDate.getText()));
                flightSchedule.setArrivalDate(LocalDate.parse(arrivalDate.getText()));
                flightSchedule.setDepartureTime(LocalTime.parse(departureTime.getText()));
                flightSchedule.setArrivalTime(LocalTime.parse(arrivalTime.getText()));

                airliner.addFlightSchedule(flightSchedule); 
                clearFields();
                JOptionPane.showMessageDialog(null, "Flight schedule is added successfully");
            }
        }
        
        /*
        else {
            
            if(isAirplaneExist == false) {
                
                int seatCols = 0;
                try {
                    seatCols = Integer.parseInt(airplaneCol.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Please enter a valid seat column number");
                    return;
                }

                int seatRows = 0;
                try{
                    seatRows = Integer.parseInt(airplaneRows.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Please enter a valid seat row number");
                    return;
                }

                Airplane newAirplane = new Airplane();
                
                newAirplane.setAirplaneName(airplaneName.getText());
                newAirplane.setSeatCol(seatCols);
                newAirplane.setSeatRow(seatRows);
                airliner.addAirplane(newAirplane);
                clearFields();
                JOptionPane.showMessageDialog(null, "Airplane Created Successfully"); 
            }
        }  */

    }//GEN-LAST:event_createFlightActionPerformed

    public void clearFields() {
        sourceCombo.setSelectedItem("-- None --");
        destinationCombo.setSelectedItem("-- None --");
        departureDate.setText("");
        arrivalDate.setText("");
        departureTime.setText("");
        arrivalTime.setText("");
    }
    
    private void departureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureDateActionPerformed

    private void backCreateFlightScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateFlightScheduleActionPerformed
        // TODO add your handling code here:
        ManageFlightSchedules flightSchedulePanel = new ManageFlightSchedules(this.panel, airlineDirectory, airplaneDirectory, airliner,masterTravelSchedule);
        this.panel.add(flightSchedulePanel, "FlightSchedule");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_backCreateFlightScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalDate;
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JButton backCreateFlightSchedule;
    private javax.swing.JButton createFlight;
    private javax.swing.JTextField departureDate;
    private javax.swing.JTextField departureTime;
    private javax.swing.JComboBox<String> destinationCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> sourceCombo;
    // End of variables declaration//GEN-END:variables
}
