/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.Flight;
import Business.MasterTravelSchedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayank
 */
public class ManageAirplanes extends javax.swing.JPanel {
    
    private AirlinerDirectory airlineDirectory;
    private AirplaneDirectory airplaneDirectory;
    private Airliner airliner;
    private JPanel panel;
    private MasterTravelSchedule masterTravelSchedule;
    
    /**
     * Creates new form CreateAirplane
     */
    public ManageAirplanes(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, Airliner airliner, MasterTravelSchedule masterTravelSchedule) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.airliner = airliner;
        this.masterTravelSchedule = masterTravelSchedule;
        populateAiplaneTable();
    }
    
    public void populateAiplaneTable() {
        DefaultTableModel dtm = (DefaultTableModel)airplaneTbl.getModel();
        dtm.setRowCount(0);
        for(Airplane f : airliner.getAirplaneList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=f;
            row[1]=f.getSeatRow();
            row[2]=f.getSeatCol();
            dtm.addRow(row);
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        addAirplaneBtn = new javax.swing.JButton();
        updateAirplaneBtn = new javax.swing.JButton();
        backAirplaneList = new javax.swing.JButton();

        airplaneTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airplane Name", "# of Rows", "# of Columns"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airplaneTbl.setRowHeight(25);
        airplaneTbl.setRowMargin(3);
        jScrollPane1.setViewportView(airplaneTbl);
        if (airplaneTbl.getColumnModel().getColumnCount() > 0) {
            airplaneTbl.getColumnModel().getColumn(0).setResizable(false);
            airplaneTbl.getColumnModel().getColumn(1).setResizable(false);
            airplaneTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Airplanes List");

        addAirplaneBtn.setText("Add Airplane");
        addAirplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirplaneBtnActionPerformed(evt);
            }
        });

        updateAirplaneBtn.setText("Update Airplane");
        updateAirplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirplaneBtnActionPerformed(evt);
            }
        });

        backAirplaneList.setText("<<Back");
        backAirplaneList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAirplaneListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(addAirplaneBtn)
                                .addGap(18, 18, 18)
                                .addComponent(updateAirplaneBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backAirplaneList)))
                        .addGap(0, 260, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backAirplaneList)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirplaneBtn)
                    .addComponent(updateAirplaneBtn))
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAirplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirplaneBtnActionPerformed
        CreateAirplanes createAirplanePanel = new CreateAirplanes(this.panel, airlineDirectory, airplaneDirectory, airliner,masterTravelSchedule);
        this.panel.add(createAirplanePanel, "CreateAirplanes");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_addAirplaneBtnActionPerformed

    private void updateAirplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirplaneBtnActionPerformed
        
        int selectedRow = airplaneTbl.getSelectedRow();
        if(selectedRow>=0){
            Airplane airplane = (Airplane)airplaneTbl.getValueAt(selectedRow, 0);
            
            UpdateAirplane updateAirplanePanel = new UpdateAirplane(this.panel, airlineDirectory, airplaneDirectory, airliner, airplane,masterTravelSchedule);
            this.panel.add(updateAirplanePanel, "UpdateAirplane");
            CardLayout layout = (CardLayout)this.panel.getLayout();
            layout.next(panel);
        }else{
            JOptionPane.showMessageDialog(null, "Please select an Airplane");
        } 
        
        /*UpdateAirplane updateAirplanePanel = new UpdateAirplane(this.panel, airlineDirectory, airplaneDirectory, airliner);
        this.panel.add(updateAirplanePanel, "UpdateAirplane");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);*/
    }//GEN-LAST:event_updateAirplaneBtnActionPerformed

    private void backAirplaneListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAirplaneListActionPerformed
        // TODO add your handling code here
        AirlinerFunction airLinerFunction = new AirlinerFunction(this.panel,  airlineDirectory,  airplaneDirectory,  airliner,  masterTravelSchedule);
        this.panel.add(airLinerFunction, "AirlinerFunction");
        CardLayout layout = (CardLayout)this.panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_backAirplaneListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirplaneBtn;
    private javax.swing.JTable airplaneTbl;
    private javax.swing.JButton backAirplaneList;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateAirplaneBtn;
    // End of variables declaration//GEN-END:variables
}
