/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.FlightSchedule;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.Flight;
import Business.MasterTravelSchedule;
import Business.Seat;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
/**
 *
 * @author Mayank
 */
public class UpdateFlight extends javax.swing.JPanel {
    
    private AirlinerDirectory airlineDirectory;
    private AirplaneDirectory airplaneDirectory;
    private JPanel panel;
    DefaultTableModel dtm;
    private Airliner airliner;
    private FlightSchedule selectedFlightSchedule;
    private Airplane selectedAirplane;
    private MasterTravelSchedule masterTravelSchedule;
    private Flight flight;
    /**
     * Creates new form CreateFlight
     */
    public UpdateFlight(JPanel panel, AirlinerDirectory airlineDirectory, AirplaneDirectory airplaneDirectory, Airliner airliner, Flight flight) {
        initComponents();
        this.panel = panel;
        this.airlineDirectory = airlineDirectory;
        this.airplaneDirectory = airplaneDirectory;
        this.airliner = airliner;
        this.masterTravelSchedule = masterTravelSchedule;
        this.flight = flight;
        this.airliner = airliner;
        dtm = (DefaultTableModel) flightSeatsTbl.getModel();
        populateAirplanes();
        populateFlightSchedules();
        populateFlightDetails();
        
    }
    
    public void populateAirplanes() {
        int count = 0, index = 0;
        
        for(Airplane a : airliner.getAirplaneList()) {
            flightAirplaneCombo.addItem(a);
            if(a == flight.getAirplane()) {
                index = count;
            }
            count++;
        }          
        flightAirplaneCombo.setSelectedIndex(index);
    }
    
    public void populateFlightSchedules() {
        int count = 0, index = 0;
        
        for(FlightSchedule s : airliner.getFlightScheduleList()) {
            flightScheduleCombo.addItem(s);
            if(s == flight.getFlightSchedule()) {
                index = count;
            }
            count++;
        }
        flightScheduleCombo.setSelectedIndex(index);
    }
    
    public void populateFlightDetails() {
        flightNameTxt.setText(flight.getFlightName());
        if(flight.isIsActive()) {
            flightStatusCombo.setSelectedIndex(0);
        }else {
            flightStatusCombo.setSelectedIndex(1);
        }       
        
        dtm = (DefaultTableModel)flightSeatsTbl.getModel();
        dtm.setRowCount(0);
        for(Seat s : flight.getFlightSeatList()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=s.getSeatName();
            row[1]=s.getPrice();
            row[2]=s.getType();
            row[3]=s.getStatus();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        flightNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flightStatusCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        flightAirplaneCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightSeatsTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        flightScheduleCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sourceTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        departureDateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        arrivalDateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        arrivalTimeTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departureTimeTxt = new javax.swing.JTextField();
        destiationTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dayTimeCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        updateFlightBtn = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Business" }));

        setPreferredSize(new java.awt.Dimension(950, 650));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Details"));

        jLabel1.setText("Flight Name");

        jLabel10.setText("Status");

        flightStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Cancel" }));

        jLabel9.setText("Airplane");

        flightAirplaneCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightAirplaneComboActionPerformed(evt);
            }
        });

        jLabel12.setText("Add Seats");

        flightSeatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Seat #", "Price", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flightSeatsTbl.setRowHeight(25);
        flightSeatsTbl.setRowMargin(3);
        flightSeatsTbl.setSelectionBackground(new java.awt.Color(228, 228, 228));
        flightSeatsTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(flightSeatsTbl);
        if (flightSeatsTbl.getColumnModel().getColumnCount() > 0) {
            flightSeatsTbl.getColumnModel().getColumn(0).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(1).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(2).setResizable(false);
            flightSeatsTbl.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(jComboBox4));
            flightSeatsTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightAirplaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(flightNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(flightStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(flightAirplaneCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Schedule Details"));

        jLabel11.setText("Select Flight Schedule to add to this Flight");

        flightScheduleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightScheduleComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Source");

        sourceTxt.setEditable(false);

        jLabel3.setText("Destination");

        departureDateTxt.setEditable(false);

        jLabel4.setText("Arrival Date");

        arrivalDateTxt.setEditable(false);
        arrivalDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalDateTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Arrival Time");

        arrivalTimeTxt.setEditable(false);

        jLabel7.setText("Destination Time");

        jLabel6.setText("Departure Date");

        departureTimeTxt.setEditable(false);
        departureTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeTxtActionPerformed(evt);
            }
        });

        destiationTxt.setEditable(false);

        jLabel8.setText("Time of Day");

        dayTimeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening", "Night" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(flightScheduleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(arrivalDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(sourceTxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arrivalTimeTxt)
                                    .addComponent(dayTimeCombo, 0, 187, Short.MAX_VALUE))))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destiationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(flightScheduleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(destiationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(arrivalDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(departureDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(arrivalTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(departureTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(dayTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel13.setText("Update a Flight");

        updateFlightBtn.setText("Update Flight");
        updateFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 189, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(updateFlightBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateFlightBtn)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void departureTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureTimeTxtActionPerformed

    private void updateFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightBtnActionPerformed
        //Flight newFlight = new Flight();
        
        flight.setFlightName(flightNameTxt.getText());
        flight.setIsActive((flightStatusCombo.getSelectedItem() == "Active"));
        flight.setFlightSchedule(selectedFlightSchedule);
        flight.setAirplane(selectedAirplane);
        
        flight.getFlightSeatList().clear();
                
        ArrayList<Seat> seatList = new ArrayList<>();
        dtm = (DefaultTableModel) flightSeatsTbl.getModel();
        int nRow = dtm.getRowCount();
        for(int i=0; i < nRow; i++) {
            Seat flightSeat = new Seat();
            flightSeat.setSeatName(flightSeatsTbl.getValueAt(i, 0).toString());
            flightSeat.setPrice((Double)flightSeatsTbl.getValueAt(i, 1));
            flightSeat.setType(flightSeatsTbl.getValueAt(i, 2).toString());
            flightSeat.setStatus(flightSeatsTbl.getValueAt(i, 3).toString());
            seatList.add(flightSeat);
        }
        flight.setFlightSeatList(seatList);        
        
        //airliner.addFlight(newFlight);
        //masterTravelSchedule.addFLight(newFlight);
    }//GEN-LAST:event_updateFlightBtnActionPerformed

    private void flightAirplaneComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightAirplaneComboActionPerformed
        selectedAirplane = (Airplane)flightAirplaneCombo.getSelectedItem();
        dtm.setRowCount(0);
        if(selectedAirplane == flight.getAirplane()) {
            dtm = (DefaultTableModel)flightSeatsTbl.getModel();            
            for(Seat s : flight.getFlightSeatList()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=s.getSeatName();
                row[1]=s.getPrice();
                row[2]=s.getType();
                row[3]=s.getStatus();
                dtm.addRow(row);
            } 
        }else {
            int totalSeats = (selectedAirplane.getSeatCol() * selectedAirplane.getSeatRow());
            dtm.setRowCount(totalSeats);
        }
        
    }//GEN-LAST:event_flightAirplaneComboActionPerformed

    private void flightScheduleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightScheduleComboActionPerformed
        selectedFlightSchedule = (FlightSchedule)flightScheduleCombo.getSelectedItem();
        
        sourceTxt.setText(selectedFlightSchedule.getSource());
        destiationTxt.setText(selectedFlightSchedule.getDestination());
        arrivalDateTxt.setText((selectedFlightSchedule.getArrivalDate()).toString());
        arrivalTimeTxt.setText((selectedFlightSchedule.getArrivalTime()).toString());
        departureDateTxt.setText((selectedFlightSchedule.getDepartureDate()).toString());
        departureTimeTxt.setText((selectedFlightSchedule.getDepartureTime()).toString());   
    }//GEN-LAST:event_flightScheduleComboActionPerformed

    private void arrivalDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalDateTxtActionPerformed
        
    }//GEN-LAST:event_arrivalDateTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalDateTxt;
    private javax.swing.JTextField arrivalTimeTxt;
    private javax.swing.JComboBox<String> dayTimeCombo;
    private javax.swing.JTextField departureDateTxt;
    private javax.swing.JTextField departureTimeTxt;
    private javax.swing.JTextField destiationTxt;
    private javax.swing.JComboBox<Airplane> flightAirplaneCombo;
    private javax.swing.JTextField flightNameTxt;
    private javax.swing.JComboBox<FlightSchedule> flightScheduleCombo;
    private javax.swing.JTable flightSeatsTbl;
    private javax.swing.JComboBox<String> flightStatusCombo;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField sourceTxt;
    private javax.swing.JButton updateFlightBtn;
    // End of variables declaration//GEN-END:variables
}
